services:
  test-runner:
    build: .
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    command: ["pytest"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

volumes:
  test_postgres_data: