global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_compose_service]
        regex: web
        action: keep
      - source_labels: [__address__]
        regex: '.*:(\d+)'
        replacement: '${1}:5001'
        target_label: __address__