global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Метрики самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Метрики всех web-контейнеров
  - job_name: 'flask_app'
    metrics_path: /metrics
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        filters:
          - name: "name"
            values: ["web"]
    relabel_configs:
      # Оставляем только контейнеры от сервиса web
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: web
        action: keep

      # Заменяем адрес на внутренний IP + порт 5001
      - source_labels: [__meta_docker_network_ip]
        target_label: __address__
        replacement: '${1}:5001'

      # Чтобы в Prometheus видно было контейнеры по имени
      - source_labels: [__meta_docker_container_name]
        target_label: instance
        regex: '/(.*)'
        replacement: '$1'
