services:
  web:
    build: ./flask_app_docker
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db

volumes:
  postgres_data: